### ISSUE TITLE
[phpBB Debug] PHP Warning: in file [ROOT]/ext/canonknipser/viewexif/event/main_listener.php on line 136: Division by zero

### ISSUE THREAD

**Issue by bcurran3** [canonknipser/viewexif#18]
I see the error:
[phpBB Debug] PHP Warning: in file [ROOT]/ext/canonknipser/viewexif/event/main_listener.php on line 136: Division by zero
pop up now and then, not sure why.  It doesn't seem to affect anything.

PHPBB 3.2.1 (happened in 3.2.0 as well), PHP 7, viewexif 1.03

**Comment by canonknipser** [comment]
As this is related to the exif data of your image, can you post please post a problematic attachment in my testing area http://canonknipser.com/viewforum.php?f=11

I'll check it soon

**Comment by canonknipser** [comment]
Did some investigation:
I assume it happens because the behavior of "list" changed between php 5.x and 7.x - order of the parameters changed: http://php.net/manual/en/function.list.php
Will try to fix as soon as possible.
Because "list" is used on different positions in the code, i need a little time (and won't fix it in 1.0.3, but in 1.1.0 already in phpBB validation queue).

**Comment by bcurran3** [comment]
Still need an example?

**Comment by canonknipser** [comment]
Don't think so, hope i can offer a fixed version in the next 2 or 3 days and publish the download link here

**Comment by canonknipser** [comment]
Hopefully I fixed this issue and got rid of "list()" complete ;)
Can you please test the attached version? 


- local unzip
- acp - manage extensions - disable
- upload files to /ext/canonknipser/viewexif
- acp - manage extensions - enable

Works with php 5.6, but actually I don't have a running php 7 test environment
[canonknipser_viewexif_1_1_0.zip](https://github.com/canonknipser/viewexif/files/1336567/canonknipser_viewexif_1_1_0.zip)

**Comment by canonknipser** [comment]
@bcurran3 : my extension was just rejected by the phpBB validation team because of some minor issues. I just finished a new package with those issues fixed:
[canonknipser_viewexif_1_1_1.zip](https://github.com/canonknipser/viewexif/files/1337491/canonknipser_viewexif_1_1_1.zip)

**Comment by bcurran3** [comment]
I just downloaded and installed 1.1.1.
Post install, massive errors, went back and disabled and deleted data and errors went away.
I'll watch for errors. I wish I would have noted which threads with pictures had problems. :(
So far seems to be working fine.

**Comment by canonknipser** [comment]
You are saying "working fine" - so, after you disabled and deleted data you enabled it again?

**Comment by bcurran3** [comment]
Yepper depper.

Deleting data seems to be a necessity.

I just viewed 10-12 threads with pictures and no problems so far.

**Comment by canonknipser** [comment]
Sounds good ;)
As a side note (but I know you know): before upgrading a phpBB extension you need to disable a existing version (normally you don't need to "delete data"), upload the new version, enable, finished.

**Comment by bcurran3** [comment]
The method you described was performed.
Disabled.
renamed directory .old
uploaded new files
enabled
fatal errors
disabled 
deleted data
enabled
working fine

**Comment by canonknipser** [comment]
Oh, I never renamed the old directory during my upgrade tests, just overwritten, maybe that's the cause.
I did upgrade from 1.0.3 to 1.1.0, 1.0.3 to 1.1.1, 1.1.0 to 1.1.1 ...

I'm afraid you did not copy the fatal errors?

**Comment by bcurran3** [comment]
No. Sorry, wanted to get it fixed ASAP. Figured if I couldn't fix the problem I'd be reporting it to you right away. If deleting data fixed the problem, error didn't matter (to me).

**Comment by canonknipser** [comment]
I close this issue because I think it is fixed now with the latest release

**Comment by bcurran3** [comment]
I have seen no problems, thanks!
